### ISSUE TITLE
Hydrawise API change

### ISSUE THREAD

**Issue by Nick-Adams-AU** [ptcryan/hydrawiser#5] opened 2020-02-19 00:33 UTC
Hi,

The Home Assistant Hydrawise integration that utilises this repo seems to have broken in the last 24-48 hours:

https://github.com/home-assistant/home-assistant/issues/31957

Looking into the error, it seems as though the Hydrawise API format may have changed recently. Unfortunately I can't find the previous API documentation so I'm only guessing from the errors.

Are you able to confirm if the current API matches your previous API documentation?

**Comment by santoal** [comment] 2020-02-19 17:31
That is correct. Json response format has changed. Looks like there is a v2 if the api which is completely different too. I’m not using this code but have adapted for Homeseer

**Comment by Nick-Adams-AU** [comment] 2020-02-20 03:01
I have received new API documents from Hydrawise:

[Hydrawise REST API.pdf](https://github.com/ptcryan/hydrawiser/files/4228552/Hydrawise.REST.API.pdf)

While it is frustrating that they have made unannounced changes to their API, it is appreciated that this API is now, according to Hunter, "updated, maintained and tested".

**Comment by santoal** [comment] 2020-02-20 04:13
I received the same info. Functionality has been cut back significantly. Also the setzone function doesn't seem to work for me as documented.

**Comment by edif30** [comment] 2020-02-20 04:14
What has been cut back?  You can still make API calls to turn on and off zones for x minutes. Besides rain click sensor (which really didn't work) what functionality went away?

**Comment by Nick-Adams-AU** [comment] 2020-02-20 04:53
I'm not sure any features have been removed but there are some fields like name and user_id that have been removed. The structure of the relays/zones has also changed substantially.

Frustratingly, Hunter don't seem to care or understand that doing this without notice is going to break things.

**Comment by santoal** [comment] 2020-02-20 05:30
Yes - lots of fields in the response which I was using are gone. Agreed on them making changes without notice. Its part of accepting the conditions of use with the REST API. I'm beginning to think v2 will be a better way to go. I managed to get some basics working through this interface here:
https://app.hydrawise.com/api/v2/graph/explore
you need to authenticate a session first by logging in through the same browser instance. Try:
{
  controller(controllerId:****) {
    id
    lastContactTime{value}
    zones {
      id
      name
      icon {
              fileName
      }
    }
  }
}
where **** is your controller id. You can pull almost any data you want.

**Comment by santoal** [comment] 2020-02-20 05:33
Also - I just alerted them that the setzone REST command doesn't work as documented in v1.4. They said they are looking in to it.

**Comment by santoal** [comment] 2020-02-20 06:02
I've had a close look at the api now. I can't even figure out a clean way of determining which zone is running. The return json structures have completely changed. I've advocated a roll-back to 1.3 and give users enough time to consider transitioning to v2.

**Comment by Nick-Adams-AU** [comment] 2020-02-20 06:16
FYI - they are making changes on the fly. "timestr" was always blank but is now populated.

I've also asked for a rollback and they said that they "had to make major changes due to GDPR and CCPA". This still doesn't explain why they made the change with zero notice. IMHO, rolling back will not happen.

You might be able to detect the running zone by checking relays[n].time == 1.

**Comment by edif30** [comment] 2020-02-20 11:52
This was back in April of 2019.  I spoke to the guy who I assume runs things over there.


Thank you for your inquiry to access the Hydrawise API.
We are currently rebuilding our API access utilizing OAuth2.

Our Beta version of OAuth2 will soon be released, to a limited number of invited business partners we expect to have full version release in the first half of 2019.

The Hydrawise API will only be provided to business partners.
API access for private use is not scheduled for release until Nov 2019.

When we are ready for your team to work on the integration we will contact you.

This will include our:
- Terms & Conditions of Use (Business Agreement)
- GDPR Privacy Agreement, which must be signed.
On the return of the signed Agreement, we will provide login details and documentation on using your OAuth2 authorization and the relevant scopes.

Regards

ANTHONY LONG
Product Manager, Hydrawise

1 760-744-5240 Main
1 760-487-2144 Direct
+61 419-669-679 Mobile 
anthony.long@hunterindustries.com

**Comment by edif30** [comment] 2020-02-20 12:25
Also, I am mistaken.  As of a few days ago when I noticed that I was getting Tracebacks in HA, I could still hit the older API and get all of the same data back via curl.  Now that I look at my data, all the older stuff is gone.  This really sucks TBH.  I'm going to have to wait until I can start using the system when winter breaks in order to test.  Hopefully in the meantime things can be sorted out.  Huge bummer here.

**Comment by Nick-Adams-AU** [comment] 2020-02-21 00:10
@edif30 Can you please remove the Hydrawise staff members personal details?

**Comment by edif30** [comment] 2020-02-21 00:16
Just noticed. Done.

**Comment by ptcryan** [comment] 2020-02-21 01:35
Hi All, I have read through the thread but I'm not completely clear what the issue is. When I wrote this I was following API v1.3. The v1.4 above doesn't appear at first glance to be much different. The statusschedule call no longer needs the hours parameter. Any other changes?

Is Hunter saying that the v1.x API is no longer supported? Based on the message above I'm not sure if the v2 API is going to be open to the public. If so that's a very disappointing.

Anyway, if I can figure out what needs to be changed to make the module compatible again I'll be glad to push out a new version.

**Comment by Nick-Adams-AU** [comment] 2020-02-21 01:44
Thanks @ptcryan! There are some more changes however they are mostly fields being removed. Things like "user_id", "watering_time", "name" and others have been removed. There's also some semantic changes around determining an active watering zone and how times are calculated/displayed.

It seems all there, just frustratingly different.

Hydrawise have confirmed that there will be no rollback so we must migrate to the new v1.4 API.

**Comment by ptcryan** [comment] 2020-02-21 01:56
OK. Thanks. I'll try to get some time this weekend to dust this off and see about updating to the latest API version. I'll need to update the HA component as well and that'll take additional time for their team to pull in the changes.

**Comment by santoal** [comment] 2020-02-21 02:19
The REST commands are semantically the same. The response structure and content is quite different. I've done a review of my own code and I'm missing data such as next scheduled run date, last run, icon images for zones, etc. As such your class structures and conversion logic in some areas will need to change. e.g. determining which zone is running needs to change.
I think you will find it may be easier to use V2 where all the data is accessible and you can preserve your logic and class structures. Just need to change the command calls to use the graph QL structure. What may be more complex is the oAuth 2 authentication which I haven't done before. Certainly easier using the API key in v1. Will be interesting to see what conclusion you get to. It depends on how much of the response data you were using and how. I'm using HomeSeer and believe someone is about to release a plug-in I think based on V2 api. I will wait to see what thats like. It's a pity as I invested about 200 hours writing my own scripts based on 1.3 which has turned out to be a waste of time.

**Closed** 2020-02-24 12:56 UTC

**Comment by ptcryan** [comment] 2020-02-24 13:03
With limited testing the module seems to be working again. There were some attributes that the new API removed and I removed them from this module. It very likely doesn't impact anyone. 

I'm not sure why the build keeps showing failed. All the Travis and Coveralls tests pass.

I will now work on uploading this to pypi.

**Comment by ptcryan** [comment] 2020-02-24 18:08
The badges are properly updating now. It just took time to update. 

The package has been pushed to pypi. V0.2

**Comment by Nick-Adams-AU** [comment] 2020-02-25 00:22
Hey @ptcryan Thanks for the update. Are we missing the rain sensor and next cycle time?

**Comment by ptcryan** [comment] 2020-02-25 03:15
Hi @Nick-Adams-AU 

The good news is it appears that the API is working with this new module version. 

The bad news is I'm going to have to do some reverse engineering to figure out how some attributes are being used in the new API. Many attributes that the Hydrawise component uses in Home Assistant have disappeared, including the ones for cycle information. Needless to say the HA component will have to be at least partially rewritten to work with the new API.

I'll start working on the HA Hydrawise component changes. I'm pretty busy these days, but I'll do my best to get this done in a timely manner.

**Comment by Nick-Adams-AU** [comment] 2020-02-25 03:36
Thanks for your help @ptcryan! It is much appreciated. I can see what you mean about the structure changes - particularly around cycle times.

Would it be easier to update this library to output the same format rather than update the library and HA?

**Comment by ptcryan** [comment] 2020-03-07 23:21
@Nick-Adams-AU I don't think just modifying the Hydrawiser library is enough. If the library changes so will the version, and HA is explicit about the version used.

Unfortunately I haven't found a way to detect rain sensor changes. Hydrawise seems to have completely removed sensor status from their published API. Strangely, they still report if a sensor is attached.

Because of these things I'm afraid I'm going to have to change both. It was a great idea though.

**Comment by Nick-Adams-AU** [comment] 2020-03-08 02:12
Good catch. I just ran a few tests to see if the HTTP API changed when the rain sensor was triggered and nothing changed. You are right, the functionality has been removed from the HTTP API.

It is however available from the GraphQL API:

https://app.hydrawise.com/api/v2/graph/explore

```
{
  controller(controllerId: YOUR_INTEGER_CONTROLLERID_FROM_HTTP_API) {
    id
    name
    zones {
      id
      name
      scheduledRuns {
        nextRun {
          id
          startTime {
            value
          }
          duration
        }
      }

    }
    sensors {
      id
      name
      status {
        active
      }
    }
  }
}
```

How do you feel about switching to the GraphQL API? It's obviously very different however it seems to have what we need.

**Comment by JustAnyGitHubUser** [comment] 2020-03-08 14:10
@ptcryan, probably a dumb question, but how can I get version 0.2 running on my system? Or will it be included in the next Home Assistant release and should I wait for that? Thanks.

**Comment by ptcryan** [comment] 2020-03-09 02:12
@Nick-Adams-AU I don't know anything about the Graph QL & oAuth 2.0 API. Do you have any documentation about it? I'm willing to consider making a GraphQL module depending on how much time it'll take.

**Comment by ptcryan** [comment] 2020-03-09 02:17
@JustAnyGitHubUser v0.2 does work, but not in HA, yet. Unfortunately, the API has changed and removed some functionality, forcing me to have to change the HA component. Even when I submit the changes to the HA project it may take a few weeks to show up in a release.

**Comment by Nick-Adams-AU** [comment] 2020-03-09 02:20
I think you could take the query from [here](https://github.com/ptcryan/hydrawiser/issues/5#issuecomment-596158060) and plug it into an example like [this](https://codewithhugo.com/python-graphql-client-requests-example-using-gql/). The resultant object looks like a pretty simple JSON structure to iterate over.

You can oauth prior to the gql query and use the resultant headers with the gql transport query.

**Comment by ptcryan** [comment] 2020-03-09 02:32
Thanks. Where can I find a list of all the available attributes that can be queried?

**Comment by Nick-Adams-AU** [comment] 2020-03-09 02:39
On the right hand side of [the explorer](https://app.hydrawise.com/api/v2/graph/explore) you can navigate through what's available and how to structure a query. It took me an hour or so to get up to speed on the structure. I think my query from above should give you all you need though.

**Comment by ptcryan** [comment] 2020-03-09 02:52
OK. Wow! I see it all now. There's a lot there. I'll take a look at it.

I also sent a message to Hydrawise support asking for documentation. Let's see how it goes.

**Comment by Nick-Adams-AU** [comment] 2020-03-09 03:34
MVP:

```python
import requests

token_url="https://app.hydrawise.com/api/v2/oauth/access-token"
client_id="hydrawise_app" # Pulled from Hydrawise dashboard auth. Will probably need official client auth to go-live
client_secret="zn3CrjglwNV1"
username="YOUR_HYDRAWISE_USERNAME"
password="YOUR_HYDRAWISE_PASSWORD"
scope="all"

payload = {
    'grant_type': 'password',
    'client_id': client_id,
    'client_secret': client_secret,
    'username': username,
    'password': password,
    'scope': scope,
}

r = requests.post(token_url,
    headers={"Content-Type":"application/x-www-form-urlencoded"},
    data=payload)

auth = r.json()

query = '''
{
  controller(controllerId: YOUR_HYDRAWISE_CONTROLLERID) {
    id
    name
    zones {
      id
      name
      scheduledRuns {
        nextRun {
          id
          startTime {
            value
          }
          duration
        }
      }

    }
    sensors {
      id
      name
      status {
        active
      }
    }
  }
}
'''
headers={'Authorization': auth["token_type"] + " " + auth["access_token"]}

resp = requests.post("https://app.hydrawise.com/api/v2/graph?scopes=all", data={ 'query': query }, headers=headers)
print(resp.text)
```

**Comment by ptcryan** [comment] 2020-03-09 03:42
Thanks! I'll give this a look tomorrow.

**Comment by Nick-Adams-AU** [comment] 2020-03-09 03:50
No worries.

Looks like the "mutation" rather than "query" schema request will allow you to execute actions (start/stop zone...etc). It may just be easier to hit these actions from the Hydrawise dashboard and record the HTTP calls.

**Comment by edif30** [comment] 2020-03-24 00:50
> MVP:
> 
> ```python
> import requests
> 
> token_url="https://app.hydrawise.com/api/v2/oauth/access-token"
> client_id="hydrawise_app" # Pulled from Hydrawise dashboard auth. Will probably need official client auth to go-live
> client_secret="zn3CrjglwNV1"
> username="YOUR_HYDRAWISE_USERNAME"
> password="YOUR_HYDRAWISE_PASSWORD"
> scope="all"
> 
> payload = {
>     'grant_type': 'password',
>     'client_id': client_id,
>     'client_secret': client_secret,
>     'username': username,
>     'password': password,
>     'scope': scope,
> }
> 
> r = requests.post(token_url,
>     headers={"Content-Type":"application/x-www-form-urlencoded"},
>     data=payload)
> 
> auth = r.json()
> 
> query = '''
> {
>   controller(controllerId: YOUR_HYDRAWISE_CONTROLLERID) {
>     id
>     name
>     zones {
>       id
>       name
>       scheduledRuns {
>         nextRun {
>           id
>           startTime {
>             value
>           }
>           duration
>         }
>       }
> 
>     }
>     sensors {
>       id
>       name
>       status {
>         active
>       }
>     }
>   }
> }
> '''
> headers={'Authorization': auth["token_type"] + " " + auth["access_token"]}
> 
> resp = requests.post("https://app.hydrawise.com/api/v2/graph?scopes=all", data={ 'query': query }, headers=headers)
> print(resp.text)
> ```

Where did you get the client secret, token_url, etc?

**Comment by Nick-Adams-AU** [comment] 2020-03-24 00:55
They use pretty standard OAuth2 on their official web dashboard so I pulled it from there (https://app.hydrawise.com/config/login). They are public knowledge but we should try to secure our own credentials obviously.

Unfortunately, Hydrawise have refused to respond to any of my emails for a number of weeks now. I'm seriously considering just removing the Hydrawise device and switching to OpenSprinkler.

**Comment by edif30** [comment] 2020-03-24 01:00
Ok I am trying to find where exactly.  I am not a web developer.  Just know how to hack my way around certain things.  I just can't find it on there.

Accidentally adding their contact info on GitHub pages sure gets their attention.  

I can't imagine or believe there are commercial products using their api.  If so, I'd be shocked.  Which means they are maintaining an API for a very limited user base.  And probably don't care.

**Comment by Nick-Adams-AU** [comment] 2020-03-24 01:05
If you log into the dashboard and use your browser dev-tools, you'll see the OAuth2 network requests which include those client-id and client-secret credentials.

So their web dashboard actually uses the GraphQL API to provide all its functionality. That gives me some hope that they won't completely kill it overnight. That said, they have shown zero technical competence with these recent changes so anything goes.

**Comment by ptcryan** [comment] 2020-03-24 01:41
I have also tried several times to reach someone at Hydrawise to request access to the API and I don't get a response. While I would like to update this library for the new API I don't think Hydrawise is interested in making this happen. I don't want to rewrite the library for v2 support without Hydrawise's blessing because they could easily break my code, and probably would if I tried to use their credentials.

Trying to find time to work on this has been difficult recently. The coronavirus has caused chaos with my household and personal schedules making it hard to get time to work on this. But, I will keep trying to find time to get this working again.

**Comment by edif30** [comment] 2020-03-24 12:47
> If you log into the dashboard and use your browser dev-tools, you'll see the OAuth2 network requests which include those client-id and client-secret credentials.
> 
> So their web dashboard actually uses the GraphQL API to provide all its functionality. That gives me some hope that they won't completely kill it overnight. That said, they have shown zero technical competence with these recent changes so anything goes.

Got it thanks!  Is it me or is the new api lacking information?  I ran the python script you built and seems like that is pretty minimal.  I may be missing something.

**Comment by Nick-Adams-AU** [comment] 2020-03-24 19:51
It's all a shambles unfortunately. We'll have to work with what we are given :(

**Comment by edif30** [comment] 2020-03-25 01:04
Ok by me.  I ended up doing curls for each of the available json blobs every minute and then parsing for individual sensors.  The setzone hasn't chagned so it wasn't that bad.  Up and running and no need for a component.

**Comment by ptcryan** [comment] 2020-04-14 16:01
An update for everyone still watching this issue. 

I have had a little discussion with Hydrawise on getting everything working again. They said they are willing to work with me, but it's still very slow communication with them.

In the mean time I have still been working (very slowly) on getting the integration with HA working again. As I mentioned before, the ability to read the rain sensor has been removed in the v1.4 API. As I'm working on this I also realized there's not way to know the suspended status of a zone. I can suspend and resume a zone, but I can't read the current suspended status. I can, however, read when a zone is running.

I'm close to issuing a pull request for the updated integration to HA. It will still support the following:
* Controller status
* Zone running status
* Switch run & stop of a zone
* Remaining time of a running zone
* The next scheduled time to run a zone

What will be missing is:
* Rain sensor status
* The ability to read the status of automatic watering (meaning the automatic watering switch will be off if the rain sensor is active)

You might be asking why I can still see the next scheduled time a zone will run, but not be able to read the suspended status. The reason is a zone will be suspended by Hydrawise automatically if the rain sensor is active. Hydrawise will also re-enable automatic scheduling when the rain sensor goes inactive. But, since I can't read the rain sensor I can't tell if a zone has been suspended because of rain, or if automatic control has been turned off.

When I make the pull request you can immediately use the HA integration if you add it to your custom components. Once the HA team approves the pull request it'll be available to everyone.

**Comment by txwindsurfer** [comment] 2020-04-14 19:30
Thank you for working on the integration.  I know you are working this into an already busy life and I really appreciate your persistence and perseverance.

**Comment by JustAnyGitHubUser** [comment] 2020-04-14 20:14
@ptcryan Thanks for investing time and effort into this integration. Much appreciated!

**Comment by ptcryan** [comment] 2020-04-20 02:41
OK. The PR has been given to Home-Assistant. You get take a look at it [here](https://github.com/home-assistant/core/pull/34448). If anyone gives it a try let me know how it goes. I've tested it with my own system and it works, with the previously mentioned limitations.

I am still trying to get someone at Hydrawise to address the API issues, but getting responses from them has been very difficult to say the least. I just hope that if or when they do they don't break the API again.

**Comment by jurrianv** [comment] 2020-05-04 14:56
I'n using HA 109.3 and still have this error:

Error during setup of component hydrawise
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 175, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/hydrawise/__init__.py", line 82, in setup
    hydrawise = Hydrawiser(user_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/hydrawiser/core.py", line 42, in __init__
    self.update_controller_info()
  File "/usr/local/lib/python3.7/site-packages/hydrawiser/core.py", line 65, in update_controller_info
    self.user_id = self.controller_status['user_id']
KeyError: 'user_id'

**Comment by ptcryan** [comment] 2020-05-04 16:39
The PR has not been merged by the HA team yet. If you want to add the PR to your HA instance before it's been included in a release you can use the custom component option. Take a look [here](https://developers.home-assistant.io/docs/creating_integration_file_structure/#where-home-assistant-looks-for-integrations) for instructions.

**Comment by txwindsurfer** [comment] 2020-05-19 03:58
David, I tried to get the new component running by: updating the 3 hydrawiser files in hassio  (/usr/local/lib/python3.7/site-packages/hydrawiser) to ver 0.2 andsetting up a hydrawise custom_component that hold the 5 new hydrawise files from this PR.  Unfortunately, I could not get all the component to work.  I have attached a screenshot below of the error message.  I am sure I am not doing something right or made an error but you indicated below to let you know if anyone give it a try.No sure what might be wrong.  I’ll try again I went back to my slightly modified 0.1 hydrawiser and got the hydrawise switch entities to work.  Is there a timeframe when the 0.2 hydrawiser with be in pypi?  Reagan From: David RyanSent: Sunday, April 19, 2020 9:41 PMTo: ptcryan/hydrawiserCc: txwindsurfer; CommentSubject: Re: [ptcryan/hydrawiser] Hydrawise API change (#5) OK. The PR has been given to Home-Assistant. You get take a look at it here. If anyone gives it a try let me know how it goes. I've tested it with my own system and it works, with the previously mentioned limitations.I am still trying to get someone at Hydrawise to address the API issues, but getting responses from them has been very difficult to say the least. I just hope that if or when they do they don't break the API again.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ptcryan** [comment] 2020-05-20 05:55
@txwindsurfer the 0.2 module is already in pypi. I run a separate instance of HA using the updated component. It's actually running on my development environment versus my main HA instance. I haven't tried to mix the new component into my regular HA environment. To be honest I'm not sure how that would work.

I'm hoping that the updated component is released soon. It's been about a month since the PR was issued.

**Comment by jjpeet** [comment] 2020-06-10 20:01
Hi @ptcryan, I notice that 0.111 hasn’t included this fix. Do you know how long it typically takes for a fix to flow through? 
Thx, JP

**Comment by ptcryan** [comment] 2020-06-10 22:07
Hi @jjpeet. The time varies, but this one is definitely on the longer side. I know the HA team was behind on reviewing PRs, but they have started reviewing mine for the Hydrawise update. My guess is it'll get into 112.

**Comment by deric** [comment] 2022-03-31 19:40
I've tried to put together a PR #10 with GraphQL support. @edif30, @Nick-Adams-AU Thanks for the code examples! I'll try to include support for rain sensors and multiple controllers. Let me know if you have any feature requests.
